name: marp-to-pages
concurrency: marp-to-pages
on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files
        run: mkdir build && cp -R assets build/assets && cp theme.css build/theme.css

      - name: Marp Build (README)
        uses: docker://marpteam/marp-cli:v2.3.0
        with:
          args: --html --allow-local-files --theme theme.css README.md -o build/index.html
        env:
          MARP_USER: root:root

      - name: Marp Build (docs folder)
        uses: docker://marpteam/marp-cli:v2.3.0
        with:
          args: --html --allow-local-files --theme theme.css -I docs/ -o build/docs
        env:
          MARP_USER: root:root

      - name: Deploy preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: main
          umbrella-dir: pr-preview

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: ./build/
          clean-exclude: pr-preview/
